---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wind5177/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --prefer-dist --no-interaction
    - cp .env.example .env || true
    - php artisan key:generate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 775 storage bootstrap/cache
 